version: "3.8"

networks:
  app:
    driver: bridge

services:
  mainDb:
    image: bitnami/postgresql:latest
    environment:
      POSTGRESQL_DATABASE: zciti_main_dev
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: postgres
    networks:
      - app
    ports:
      - "5432:5432"
  chatDb:
    image: bitnami/postgresql:latest
    environment:
      POSTGRESQL_DATABASE: zciti_chat_dev
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: postgres
    networks:
      - app
    ports:
      - "5433:5432"
  redis:
    image: bitnami/redis:latest
    environment:
      REDIS_PASSWORD: redis
      REDIS_DATABASE: 1
    networks:
      - app
    ports:
      - "6489:6379"
#  example:
#    build:
#      context: .
#      dockerfile: build/Dockerfile${CUSTOM}
#    depends_on:
#      - postgres
#    links:
#      - postgres
#    volumes:
#      - .:/app
#    networks:
#      - app
#    ports:
#      - "8080:8080"
