# Configuration vars for cmd/app
[app]
name = "Fiber starter"
port = "8000"
idle-timeout = 5 # As seconds
print-routes = false
prefork = true
production = false

[app.tls]
enable = false
cert-file = "./storage/selfsigned.crt"
key-file = "./storage/selfsigned.key"

[db.postgres]
dsn = "postgresql://postgres:postgres@localhost:5432/fiber_starter" # <driver>://<username>:<password>@<host>:<port>/<database>

[services.messageWay]
apiKey = "26510b7869bc5d2f0fe16bf0f94d38eb"

[logger]
time-format = "" # https://pkg.go.dev/time#pkg-constants, https://github.com/rs/zerolog/blob/master/api.go#L10 
level = 0 # panic -> 5, fatal -> 4, error -> 3, warn -> 2, info -> 1, debug -> 0, trace -> -1
prettier = true

[middleware.compress]
enable = true
level = 1

[middleware.recover]
enable = true

[middleware.monitor]
enable = false
path = "/monitor"

[middleware.pprof]
enable = true

[middleware.limiter]
enable = false
max = 20
expiration_seconds = 60

[middleware.jwt]
secret = "apom$dpaom%dpaosmdpoamu2n4i2@$02"
expiration_seconds = 86400

[middleware.filesystem]
enable = false
browse = true
max_age = 3600
index = "index.html"
root = "./storage/public"