# Configuration vars for cmd/app
[app]
name = "Fiber starter"
backendDomain = "http://example.com"
frontenddomain = "http://example.com"
port = "8000"
idle-timeout = 5 # As seconds
print-routes = false
prefork = true
production = false

[app.tls]
enable = false
cert-file = "./storage/selfsigned.crt"
key-file = "./storage/selfsigned.key"

[db.main]
url = "" # <driver>://<username>:<password>@<host>:<port>/<database>

[db.chat]
url = ""  # <driver>://<username>:<password>@<host>:<port>/<database>

[services.messageWay]
apiKey = ""

[services.googleRecaptcha]
secretKey = ""

[services.zarinpal]
merchantID = ""
Sandbox = false

[logger]
time-format = "" # https://pkg.go.dev/time#pkg-constants, https://github.com/rs/zerolog/blob/master/api.go#L10 
level = 0 # panic -> 5, fatal -> 4, error -> 3, warn -> 2, info -> 1, debug -> 0, trace -> -1
prettier = true

[redis]
url="" # redis://<user>:<pass>@127.0.0.1:6379/<db>

[middleware.compress]
enable = true
level = 1

[middleware.recover]
enable = true

[middleware.monitor]
enable = false
path = "/monitor"

[middleware.pprof]
enable = true

[middleware.limiter]
enable = false
max = 20
expiration_seconds = 60

[middleware.jwt]
secret = ""
expiration_seconds = 86400

[middleware.filesystem]
enable = false
browse = true
max_age = 3600
index = "index.html"
root = "./storage/public"